**Pytorch and HuggingFace (Hacker's Guide)** [Requires GPU]

In [4]:
# pip uninstall transformers

In [3]:
# pip install git+https://github.com/huggingface/transformers

In [11]:
# pip install accelerate bitsandbytes

In [18]:
# pip install auto-gptq optimum

In [37]:
# pip install sentence-transformers

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

In [2]:
import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

In [3]:
from google.colab import userdata
userdata.get('HF_TOKEN')

'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'

In [4]:
# mn = "meta-llama/Llama-2-7b-hf"
mn = "stabilityai/stable-code-3b"

In [5]:
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, load_in_8bit=True)

The repository for stabilityai/stable-code-3b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stable-code-3b.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
The repository for stabilityai/stable-code-3b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stable-code-3b.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [6]:
tokr = AutoTokenizer.from_pretrained(mn)
prompt = "Jeremy Howard is a "
toks = tokr(prompt, return_tensors='pt')

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [7]:
toks

{'input_ids': tensor([[20723,  2013,    90, 15197,   310,   247,   209]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [8]:
tokr.batch_decode(toks['input_ids'])

['Jeremy Howard is a ']

In [9]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


CPU times: user 7.11 s, sys: 591 ms, total: 7.7 s
Wall time: 10.3 s


tensor([[20723,  2013,    90, 15197,   310,   247,   209,   187,     4, 50276,
          2641,    15,    37,    15,  5974,   275,   253,  4487,   273, 19179,
          6875,   387]])

In [10]:
tokr.batch_decode(res)

['Jeremy Howard is a \n#  Ph.D. student in the Department of Computer Science at']

In [11]:
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, torch_dtype=torch.bfloat16)

The repository for stabilityai/stable-code-3b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stable-code-3b.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [12]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


CPU times: user 748 ms, sys: 2.23 ms, total: 751 ms
Wall time: 851 ms


tensor([[20723,  2013,    90, 15197,   310,   247,   209,   187,     4, 50275,
          2641,    15,    37,    15,  5974,   275,   253,  4487,   273, 19179,
          6875,   387]])

In [13]:
mn = "TheBloke/stable-code-3b-GPTQ"
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, torch_dtype=torch.float16)

The repository for TheBloke/stable-code-3b-GPTQ contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/TheBloke/stable-code-3b-GPTQ.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
The repository for TheBloke/stable-code-3b-GPTQ contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/TheBloke/stable-code-3b-GPTQ.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


model.safetensors:   0%|          | 0.00/1.84G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [14]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


CPU times: user 574 ms, sys: 177 µs, total: 574 ms
Wall time: 601 ms


tensor([[20723,  2013,    90, 15197,   310,   247,   209,   187,     4, 50276,
         12311,  3331,   273,  7477,    15,   187,     4, 50276,    42,   717,
           247,  1175]])

In [15]:
def gen(p, maxlen=15, sample=True):
  toks = tokr(p, return_tensors='pt')
  res = model.generate(**toks.to("cuda"), max_new_tokens=maxlen, do_sample=sample).to('cpu')
  return tokr.batch_decode(res)

In [16]:
gen(prompt, 50)

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


['Jeremy Howard is a \nspecialized artist, and his signature is alluding to a story of his own: An \nintensely personal experience that led to the making of a brand new work of \nart.</P>\n<P>-<NAME>, The']

In [17]:
mn = "stabilityai/stablelm-zephyr-3b"
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, torch_dtype=torch.bfloat16)

config.json:   0%|          | 0.00/840 [00:00<?, ?B/s]

The repository for stabilityai/stablelm-zephyr-3b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stablelm-zephyr-3b.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


configuration_stablelm_epoch.py:   0%|          | 0.00/5.49k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/stabilityai/stablelm-zephyr-3b:
- configuration_stablelm_epoch.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


The repository for stabilityai/stablelm-zephyr-3b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stablelm-zephyr-3b.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


modeling_stablelm_epoch.py:   0%|          | 0.00/38.4k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/stabilityai/stablelm-zephyr-3b:
- modeling_stablelm_epoch.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors:   0%|          | 0.00/5.59G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [29]:
sb_sys = "<|user|>\nList 3 synonyms for the word 'tiny'\n<|assistant|>\n1. Dwarf\n2. Little\n3. Petite"

In [30]:
def mk_prompt(user, syst=sb_sys):
  return f"{syst}### User:{user}\n\n### Assistant:\n"

In [31]:
ques = "Who is Jeremy Howard?"

In [32]:
gen(mk_prompt(ques), 150)

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


['<|user|>\nList 3 synonyms for the word \'tiny\'\n<|assistant|>\n1. Dwarf\n2. Little\n3. Petite### User:Who is Jeremy Howard?\n\n### Assistant:\nJeremy Howard is an American television producer, writer, director, composer, and lyricist. He is best known for his work on the animated television series Fruit Bins, which he co-created alongside Tom Rueger. In this series, a family runs an unsuccessful fruit stand until they discover a magical mystery fruit that makes their stand prosperous. \n\nHoward has also worked on other projects as a composer and songwriter. Some of his compositions include "We Are Friends" for the animated TV show "Alright!, Lemonade Ivy Garden," and "Happy Birthday Song" for the program "Oobi." In addition to his work in television and music, Jeremy has also directed several films, including "Boat Ball" and']

Retrieval Augmented Generation

In [22]:
from wikipediaapi import Wikipedia

In [23]:
wiki = Wikipedia('JeremyHowardBot/0.0', 'en')
jh_page = wiki.page('Jeremy_Howard_(entrepreneur)').text
jh_page = jh_page.split('\nReferences\n')[0]

In [24]:
print(jh_page[:500])

Jeremy Howard (born 13 November 1973) is an Australian data scientist, entrepreneur, and educator.He is the co-founder of fast.ai, where he teaches introductory courses, develops software, and conducts research in the area of deep learning.
Previously he founded and led Fastmail, Optimal Decisions Group, and Enlitic. He was President and Chief Scientist of Kaggle.
Early in the COVID-19 epidemic he was a leading advocate for masking.

Early life
Howard was born in London, United Kingdom, and move


In [25]:
len(jh_page.split())

613

In [26]:
ques_ctx = f"""Answer the question with the help of the provided context.

## Context

{jh_page}

## Question

{ques}"""

In [33]:
res = gen(mk_prompt(ques_ctx), 300)

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


In [34]:
print(res[0].split('### Assistant:\n')[1])

Jeremy Howard is an Australian data scientist, entrepreneur, and educator. He co-founded fast.ai, a research institute focused on making Deep Learning more accessible, and teaches introductory courses both online and in-person. Additionally, he has served as the President and Chief Scientist of Kaggle and has contributed to various open-source projects as a developer.<|endoftext|>


In [38]:
from sentence_transformers import SentenceTransformer

In [40]:
emb_model = SentenceTransformer("BAAI/bge-small-en-v1.5", device=0)

.gitattributes:   0%|          | 0.00/1.52k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/90.3k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/134M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [42]:
jh = jh_page.split('\n\n')[0]
print(jh)

Jeremy Howard (born 13 November 1973) is an Australian data scientist, entrepreneur, and educator.He is the co-founder of fast.ai, where he teaches introductory courses, develops software, and conducts research in the area of deep learning.
Previously he founded and led Fastmail, Optimal Decisions Group, and Enlitic. He was President and Chief Scientist of Kaggle.
Early in the COVID-19 epidemic he was a leading advocate for masking.


In [44]:
tb_page = wiki.page('Tony_Blair').text.split('\nReferences\n')[0]

In [45]:
tb = tb_page.split('\n\n')[0]
print(tb[:380])

Sir Anthony Charles Lynton Blair  (born 6 May 1953) is a British politician who served as Prime Minister of the United Kingdom from 1997 to 2007 and Leader of the Labour Party from 1994 to 2007. He served as Leader of the Opposition from 1994 to 1997 and held various shadow cabinet posts from 1987 to 1994. Blair was Member of Parliament (MP) for Sedgefield from 1983 to 2007. He


In [46]:
q_emb, jh_emb, tb_emb = emb_model.encode([ques,jh,tb], convert_to_tensor=True)

In [47]:
tb_emb.shape

torch.Size([384])

In [48]:
import torch.nn.functional as F

In [49]:
F.cosine_similarity(q_emb, jh_emb, dim=0)

tensor(0.7991, device='cuda:0')

In [50]:
F.cosine_similarity(q_emb, tb_emb, dim=0)

tensor(0.5381, device='cuda:0')